### ISSUE TITLE
Example + 1step to .click first result - 0%

### ISSUE THREAD

**Issue by r3velations** [tomLendy/learning-Nightmare#4]
#### Explanation
- Currently my example launches electron, pulls up [duckduckgo.com](https//www.duckduckgo.com) and searches for "github nightmare". I would like to take this one step further and have the system then go and .click the first link. 

#### Task(s) 
- [x] Research additional steps to complete issue
- [x] Code additional steps
- [x] Test additional steps
- [x] Merge code into /src/example.js
